name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'

      - name: Go build
        env:
          GOOS: windows
          GOARCH: 386
        run: |
          go build -o rover-mems.exe ./...

      - name: Zip exe and web files
        run: |
          tar -a -c -f rover-mems.zip rover-mems.exe web-static
